title: Hi! I'm Bruno # your name (or website title) here
logo: "/images/10.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a passionate and experienced Android developer with a background in financial auditing. In the past few years, I have been working as the head of the mobile development team at a startup, where I have led the design and implementation of innovative and user-friendly applications. I have also leveraged my skills and knowledge from my previous career in the financial sector, where I was a leader in auditing and compliance. I enjoy learning new technologies and solving challenging problems in the mobile domain.
  <br><br>
  With more than 10 years of professional experience, I have a solid understanding of financial processes and regulations, as well as analytical and problem-solving skills. I am always eager to learn new technologies and create innovative solutions that meet the needs of the market and the users.
  <br><br>
  <a href="https://www.linkedin.com/in/bmanchinelli/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-7409JMLPYK # your Google Analytics tracking ID here
