title: Hi! I'm Bruno # your name (or website title) here
logo: "/images/10.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an experienced Accountant and financial advisor, and since 2018 I am working on a career change into programming. 
  <br><br>
  I am looking for experience in an enabling professional environment to reach my goal with challenging, inspiring, and fulfilling projects. 
  <br><br>
  <a href="https://www.linkedin.com/in/bmanchinelli/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
